CREATE SCHEMA IF NOT EXIST ubs;

INSERT INTO ROLE (ROLE_ID, NAME) VALUES (NEXTVAL('SEQ_ROLE'),'ROLE_ADMIN'),(NEXTVAL('SEQ_ROLE'),'ROLE_USER');
INSERT INTO USER_UBS (USER_ID, NAME, USERNAME, PASSWORD, CREATION_DATE) VALUES (NEXTVAL('SEQ_USER'), 'Administrador', 'admin', '$2a$10$nrK5z/xQ/TOXZ3VAkdKmqeBN16a9sTj6cyV6ayVIFq21XSG5fYcrC', '2020-10-12 16:07:37');
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES ((SELECT ROLE_ID FROM ROLE WHERE NAME = 'ROLE_ADMIN'), (SELECT USER_ID FROM USER_UBS WHERE USERNAME = 'admin'));
INSERT INTO USER_UBS (USER_ID, NAME, USERNAME, PASSWORD, CREATION_DATE) VALUES (NEXTVAL('SEQ_USER'), 'Usuário teste', 'user.teste', '$2a$10$nrK5z/xQ/TOXZ3VAkdKmqeBN16a9sTj6cyV6ayVIFq21XSG5fYcrC', '2020-10-12 16:07:37');
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES ((SELECT ROLE_ID FROM ROLE WHERE NAME = 'ROLE_USER'), (SELECT USER_ID FROM USER_UBS WHERE USERNAME = 'user.teste'));
INSERT INTO USER_UBS (USER_ID, NAME, USERNAME, PASSWORD, CREATION_DATE) VALUES (NEXTVAL('SEQ_USER'), 'Usuário teste 2', 'user.teste2', '$2a$10$nrK5z/xQ/TOXZ3VAkdKmqeBN16a9sTj6cyV6ayVIFq21XSG5fYcrC', '2020-10-12 16:07:37');
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES ((SELECT ROLE_ID FROM ROLE WHERE NAME = 'ROLE_USER'), (SELECT USER_ID FROM USER_UBS WHERE USERNAME = 'user.teste2'));
